### ISSUE TITLE
TypeError: Cannot read property 'enabled' of undefined

### ISSUE THREAD

**Issue by ehubbell** [sportly/ember-cli-mixpanel-service#6]
I just did a fresh install and am getting this message. I referenced closed issue #1 but am still returning a similar error: `TypeError: Cannot read property 'enabled' of undefined`. Thoughts?

**environment**
`Ember 1.13.2`
`Ember Cli 0.2.7`

**package.json**

``` javascript
"ember-cli-mixpanel-service": "0.0.8",
```

**config/environment**

``` javascript
if (environment === 'production') {
    ENV.APP.dataHost = 'https://api.myhubapp.com';
    ENV.mixpanel = {
      enabled: true,
      LOG_EVENT_TRACKING: false,
      token: 'my_token'
    };
```

**Comment by kylenathan** [comment]
Hi @ehubbell - from the snippet it looks like you're defining the config for production only (not for dev)? If you're then getting this error on dev (ember serve) its because you'll need to define the default/dev settings.

**Comment by ehubbell** [comment]
Hi @kylenathan that worked! Thanks for the help.

**Comment by kylenathan** [comment]
Great! :+1:
